#! /bin/sh

wiki_url="https://devel.rtems.org/wiki/GCI/Coding/AddPerSectionSupportToBSPs"

infile=bsps_needing_sections.txt
outfile=tasks.csv

if [ ! -x ../get_mentor ] ; then
  echo "get_mentor is not executable"
  exit 1
fi
num=1

generate_tasks()
{
  # row headings have to be printed
  # NEW - title,description,max_instances,mentors,tags,is_beginner,categories,time_to_complete_in_days,private_metadata

  bsp=$1

  title="Add Per Function Sections to ${bsp} BSP"
  desc=""
  desc="${desc}Compiler and Linker flags can make a big difference on the size and speed of programs."
  desc="${desc} This task consists of adding per function section support to"
  desc="${desc} ${bsp} BSP per these [instructions](${wiki_url})."
  desc="${desc} The outcome of this task is a patch and report of the size difference achieved."
  max_instances="1"
  mentors=`../get_mentor ${num}`
  tags="C, BSP"
  is_beginner="0"
  # 1: Coding. 2: User Interface. 3: Documentation & Training. 
  # 4: Quality Assurance. 5: Outreach & Research.
  categories="1,4"
  time_to_complete="5"

# NEW - title,description,max_instances,mentors,tags,is_beginner,categories,time_to_complete_in_days,private_metadata
  echo "${title}, \"${desc}\",${max_instances},\"joel.sherrill@gmail.com,${mentors}\",\"${tags}\",${is_beginner},\"${categories}\",${time_to_complete}, \"function sections BSP\""
  num=`expr ${num} + 1`
}

echo "name,description,max_instances,mentors,tags,is_beginner,categories,time_to_complete_in_days,private_metadata" >${outfile}
cat ${infile} | while read line
do
  bsp=${line}
  generate_tasks ${bsp}
done >>${outfile}

wc -l *.csv
exit 0
