#! /bin/sh

usage()
{
  echo "gen_bsps_needing_sections RTEMS_DIR"
}

if [ $# -ne 1 ] ; then
  usage
  exit 1
fi

if [ ! -d $1 ] ; then
  echo $1 does not exist
  exit 1
fi

cd $1

if [ ! -d bsps ] ; then
  echo "Must be run from the top of the RTEMS source tree"
  exit 1
fi

find bsps -name "config" | while read CFG
do
  lines=`grep "l,--gc-sections" ${CFG}/* 2>/dev/null | grep -v "^#"| wc -l`
  if [ $lines -eq 0 ] ; then
    echo "${CFG}"
  fi
  #grep "function-sections" ${CFG}/*

done | cut -d'/' -f2-3
