#! /bin/sh

wiki_url="https://devel.rtems.org/wiki/GCI/Coding/AddPOSIXMethodSignatureComplianceTests"

infile=TBDs
outfile=tasks.csv

if [ ! -x ../get_mentor ] ; then
  echo "get_mentor is not executable"
  exit 1
fi
num=1

generate_tasks()
{
  # row headings have to be printed
  # NEW - title,description,max_instances,mentors,tags,is_beginner,categories,time_to_complete_in_days,private_metadata

  name=$1
  task=$2

  title="Implement POSIX API Signature Compliance Tests for ${header} File"
  desc=""
  desc="${desc} "This 
  desc="${desc} This task consists of converting a Wiki page to Rest and"
  desc="${desc} inserting it into the appropriate section in the RTEMS "
  desc="${desc} Software Engineering Handbook. You will be editing the "
  desc="${desc} file (${name}) to: ${task}"
  desc="${desc} "
  desc="${desc} Turn the URL into a comment -- do NOT delete it."
  desc="${desc} "
  desc="${desc} The RTEMS Software Engineering Handbook is currently only "
  desc="${desc} available on the sw_eng_hb branch of the personal git repo " 
  desc="${desc} git://git.rtems.org/joel/rtems-docs.git. All work should be "
  desc="${desc} against the eng/ subdirectory of this branch."
  desc="${desc} "
  desc="${desc} The original document this outline is based on is at "
  desc="${desc} https://ftp.rtems.org/pub/rtems/people/joel/sw_eng_hb/. "
  desc="${desc} "
  desc="${desc} If there are questions, ask on gci@rtems.org."
  desc="${desc} "
  desc="${desc} The outcome of this task is a patch against the document."
  max_instances="1"
  mentors=`../get_mentor ${num}`
  tags="C, POSIX, tests, compliance, conformance"
  is_beginner="0"
  # 1: Coding. 2: User Interface. 3: Documentation & Training. 
  # 4: Quality Assurance. 5: Outreach & Research.
  categories="4,3"
  time_to_complete="5"

# NEW - title,description,max_instances,mentors,tags,is_beginner,categories,time_to_complete_in_days,private_metadata
  echo "${title}, \"${desc}\",${max_instances},\"joel.sherrill@gmail.com,${mentors}\",\"${tags}\",${is_beginner},\"${categories}\",${time_to_complete}, \"POSIX API Compliance\""
  num=`expr ${num} + 1`
}

echo "name,description,max_instances,mentors,tags,is_beginner,categories,time_to_complete_in_days,private_metadata" >${outfile}
cat ${infile} | while read line
do
  name=${line}
  read task
  
  generate_tasks ${name} "${line}"
done >>${outfile}

wc -l *.csv
exit 0
