#! /bin/sh

if [ $# -ne 1 ] ; then
  echo "usage: $0 number"
  exit 1
fi

Number=$1

isNumber()
{
  if [ $Number -ne 0 -o $Number -eq 0 2>/dev/null ]; then
    return 0
  fi
  return 1
}

status=`isNumber ${Number}`
if [ $? -ne 0 ] ; then
  echo "${Number} is NOT a number"
  exit 1
fi

## CHANGE ME WHEN LIST CHANGES
NumMentors=12
remainder=`expr ${Number} % ${NumMentors}`
case ${remainder} in
  0) mentor=joel.sherrill@gmail.com ;;
  1) mentor=gedarebloom@gmail.com ;;
  2) mentor=chrisj@rtems.org ;;
  3) mentor=heshamelmatary@gmail.com ;;
  4) mentor=amardtakhar@gmail.com ;;
  5) mentor=aanjhan@gmail.com ;;
  6) mentor=hiddenpearls@gmail.com ;;
  7) mentor=lmy2010lmy@gmail.com ;;
  8) mentor=amaan.cheval@gmail.com ;;
  9) mentor=dev.madaari@gmail.com ;;
  10) mentor=zaidiaunali9@gmail.com ;;
  11) mentor=vijaykumar9597@gmail.com ;;
  #12) mentor=scott@zemericks.com ;;
  #13) mentor=cibrario@polito.it ;;
  *) echo "What?" ; exit 1 ;;
esac
echo -n ${mentor}
exit 0
