#! /bin/sh

wiki_url="http://wiki.rtems.org/wiki/index.php/GoogleCodeInProjects#Refactoring_Board_Support_Packages"
outfile=tasks_bsp.csv

if [[ -z $1 ]]; then
  echo "Starting task no not given";
  exit
fi

if [[ -z $2 ]]; then
  echo "No of tasks to be generated not given";
  exit
fi


start_number=$1
total=$2

task[0]=""
task[1]="arm/gumstix : Move bsp_reset() in startup/bspstart.c to startup/bspreset.c"
task[2]="powerpc/beatnik : Move bsp_reset() in startup/reboot.c to startup/bspreset.c"
task[3]="powerpc/mpc55xxevb : Move bsp_reset() in startup/reset.c  to startup/bspreset.c"
task[4]="powerpc/mpc55xxevb : Move bsp_work_area_initialize() in startup/bspworkareainit.c to startup/bspgetworkarea.c"
task[5]="powerpc/mpc55xxevb : startup/start.S should be moved to start/start.S"

generate_tasks()
{

  num=${start_number}
  task_done=0

  while :
  do
    title="BSP Refactoring Task #${num}"
    desc=""
    desc="${desc} This task consists of refactoring BSP code."
    desc="${desc} The instructions to carry out this category of tasks"
    desc="${desc} can be found at <a href=${wiki_url}>${wiki_url}</a>."
    desc="${desc} The problem statement for this particular task is :"
    
    text=${task[$num]}
    desc="${desc} ${text}"

    time_to_complete="72"
    mentor_no=$(( $num-1 % 10 ))
    mentors=`../get_mentor ${mentor_no}`
    type="Code"
    tags="C"

    echo "${title}, ${desc},${time_to_complete},${mentors},${type},\"${tags}\""
    num=`expr ${num} + 1`
    if [ ${num} -gt ${total} ] ; then
      break
    fi
  done
}

generate_tasks \
  >$outfile

wc -l *.csv
exit 0