#! /bin/sh

if [ $# -ne 1 ] ; then
  echo "usage: $0 number"
  exit 1
fi

Number=$1

isNumber()
{
  if [ $Number -ne 0 -o $Number -eq 0 2>/dev/null ]; then
    return 0
  fi
  return 1
}

status=`isNumber ${Number}`
if [ $? -ne 0 ] ; then
  echo "${Number} is NOT a number"
  exit 1
fi

## CHANGE ME WHEN LIST CHANGES
NumMentors=5
remainder=`expr ${Number} % ${NumMentors}`
case ${remainder} in
  0) mentor=joel_sherrill ;;
  1) mentor=gedare ;;
  2) mentor=crempel2 ;;
  3) mentor=hiddenpearls ;;
  4) mentor=vipulnayyar ;;
#  5) mentor=sebhub ;;
#  6) mentor=amartakhar ;;
#  7) mentor=cdcs ;;
#  8) mentor=oarmark ;;
  *) echo "What?" ; exit 1 ;;
esac
echo -n ${mentor}
exit 0
